name: mbtmi
description: 2022 SW Joint Hackathon

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.3
  provider: ^6.0.3
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/fonts/GmarketSansTTFBold.ttf
          weight: 700
