name: mbtmi
description: 2022 SW Joint Hackathon

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.3
  provider: ^6.0.3
  kakao_flutter_sdk_user: ^1.1.1
  change_app_package_name: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  dio: ^4.0.6
  json_annotation: ^4.5.0
  package_info: ^2.0.2
  package_info_plus: ^1.4.2
  platform: ^3.1.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0
  get: ^4.6.5
  carousel_slider: ^4.1.1
  syncfusion_flutter_charts: ^20.1.61
  dotted_line: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile/

  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
          weight: 500
        - asset: assets/fonts/GmarketSansTTFBold.ttf
          weight: 700
